# Numpy Basics

## Introduction to Modules, Packages, Libraries and Frameworks

### Modules

#### What is a module?

Modules are python program files saved with the .py extension desgined to solve certain problemsand allow reusability of code. Modules in Python provides us the flexibility to organize the code in a logical way. Modules allows us to break a large, unwieldy programming task into separate, smaller, more manageable subtasks. A module can define functions, classes, and variables. A module can also include runnable code.

#### Advantages of modules

- **Simplicity**: Rather than focusing on the entire problem at hand, a module typically focuses on one relatively small portion of the problem. This makes development easier and less error-prone.
- **Maintainability**: Modules are typically designed so that they enforce logical boundaries between different problem domains.This makes it more viable for a team of many programmers to work collaboratively on a large application.
- **Reusability**:Functionality defined in a single module can be easily reused (through an appropriately defined interface) by other parts of the application. This eliminates the need to duplicate code.
- **Scoping**: Modules typically define a separate namespace, which helps avoid collisions between identifiers in different areas of a program.

#### Examples of Modules

##### Built-in Modules

- **sys**: This module provides functions and variables used to manipulate different parts of the Python runtime environment.
- **time**: This module has many time related functions.
- **math**: This module presents commonly required mathematical functions.
- **os**: This module has functions to perform many tasks of operating system.
- **random**: Python’s standard library contains random module which defines various functions for handling randomization. 

### Packages

#### What is a package?

A package is a collection of various modules designed to perform similiar tasks. Physcially, it consists of Python modules containing an additional `__init__.py` file. , which distinguishes a package from a directory that is supposed to contain multiple Python scripts. Packages can be nested to multiple depths if each corresponding directory contains its own `__init__.py` file. `__init__.py` helps the Python interpreter to recognise the folder as package. It also specifies the resources to be imported from the modules. If the `__init__.py` is empty this means that all the functions of the modules will be imported. All the packages are modules but not all modules are packages.

It has same advantages as that of a module, but in a broader perspective. 

#### Examples of Packages

- **pip**: This package allows the users to install and manage packages in Python.- **
- **pytest**: It provides a variety of modules to test new code, including small unit tests or complex functional tests.
- **Pandas**: It is a Python package for fast and efficient processing of tabular data, time series, matrix data, etc.
- **NumPy**: NumPy is the essential package for scientific and mathematical computing in Python.

### Libraries

#### What is a library?

A library is an umbrella term referring to a reusable chunk of code. Actually, this term is often used interchangeably with “Python package” because packages can also contain modules and other packages (subpackages). However, it is often assumed that while a package is a collection of modules, a library is a collection of packages.

#### Examples of Libraries

- **Matplotlib**: Standard library for generating data visualizations in Python. It supports building basic two-dimensional graphs as well as more complex animated and interactive visualizations.
- **Pytorch**: It is an open-source deep-learning library built by Facebook’s AI Research lab to implement advanced neural networks and cutting-edge research ideas in industry and academia.
- **Scikit-learn**: It is the most useful and robust library for machine learning in Python.

### Frameworks

#### What is a Framework?

Similar to libraries, Python frameworks are a collection of modules and packages that help programmers to fast track the development process. However, frameworks are usually more complex than libraries. Also, while libraries contain packages that perform specific operations, frameworks contain the basic flow and architecture of the application.

#### Examples of a Framework

- **Tensorflow**: It free and open-source software library for machine learning and artificial intelligence.
- **Django**: It is a Python framework for building web applications with less coding.
- **Flask**: It is also a web development framework that is known for its lightweight and modular design.

## Importing modules

To use any of these in our project, we use the keyword `import`. To import a module, we use
`import <module_name>`

In [1]:
import math

We can also use `as` keyword to provide a short name for the module. Some of the common short names are:
- `numpy as np`
- `pandas as pd`
- `matplotlib.pyplot as plt`
- `tensorflow as tf`

In [2]:
import numpy as np

To import only certain functions, classes and variables we use `from <module_name> import <name(s)>`

In [5]:
from numpy import array

## Numpy arrays

Numpy arrays are powerful multidimensional arrays of values, all of the same type, and is indexed by a tuple of nonnegative integers for efficient and fast computation of arrays and matrices. To provide a perspective, adding a scaler value to 10000 elements of a Numpy array was 120 times faster than performing same operation to a Python List. Because the Numpy array is densely packed in memory due to its homogeneous type, it also frees the memory faster.
So overall a task executed in Numpy is around 5 to 100 times faster than the standard python list, which is a significant leap in terms of speed.

#### The main reasons behind the fast speed of Numpy

- Numpy array is a collection of similar data-types that are densely packed in memory. A Python list can have different data-types, which puts lots of extra constraints while doing computation on it.
- Numpy is able to divide a task into multiple subtasks and process them parallelly.
- Numpy functions are implemented in C which again makes it faster compared to Python Lists.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets

In [6]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


The number of dimensions is called the rank of the array.
The shape of an array is a tuple of integers giving the size of the array along each dimension. It can be called using `.shape`.

To access the multiple values/indices of a numpy array, we can provide a list of indices.

In [13]:
print(a[[0,2]])

[5 3]


Similar to Lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array. Slicing a Python list, creates a copy of the original list while sliced array in numpy referes to the original array. 

In [9]:
# b = [[ 1 2 3]
#      [ 4 5 6]]

c = b[:2, 1:2] # The numpy array is sliced from 0 to 2(exclusive) rows
               # and sliced from 1 to 2(exlusive)
print(c)

[[2]
 [5]]


## Vectorization

The **vectorization** is a powerful ability within NumPy to express operations as occurring on entire arrays rather than their individual elements. When looping over an array or any data structure in Python, there’s a lot of overhead involved. Vectorized operations in NumPy delegate the looping internally to highly optimized C and Fortran functions, making for cleaner and faster Python code.

In [17]:
# instead of this
s = 0
for i in b:
    for j in i:
        s += j
print(s)

print(np.sum(b)) # we can do this instead

21
21


## Broadcasting

The term **broadcasting** refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python as we know that Numpy implemented in C. It does this without making needless copies of data and which leads to efficient algorithm implementations. 

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when:

- they are equal, or
- one of them is 1

In [16]:
d = b * a
# d = [[ 1*5 2*2 3*3]
#      [ 4*5 5*2 6*3]]
print(d)

e = b+b
# e = [[ 1+1 2+2 3+3]
#      [ 4+4 5+5 6+6]]
print(e)

[[ 5  4  9]
 [20 10 18]]
[[ 2  4  6]
 [ 8 10 12]]


Not only arithmetic operations are allowed on arrays, we can also use logical operations on it as well

In [18]:
print(a)
print(a>2)

[5 2 3]
[ True False  True]


In [19]:
print(a[a>2]) # Print values that are greater than 2

[5 3]


## Important Numpy Functions

`zeros(shape)`: It create an array of all zeros of given shape

In [21]:
print(np.zeros(6))
print(np.zeros((5,3)))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


`eye(N)`: It creates a Identity matrix of size N

In [24]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


`arange([start, ]stop, [step, ])`: It returns evenly spaced values within a given interval. Similiar to range.

In [26]:
print(np.arange(3,7))

[3 4 5 6]


`linspace(start, stop)`: It returns evenly spaced numbers/floats over a specified interval.

In [27]:
print(np.linspace(3.8,7.1,4))

[3.8 4.9 6.  7.1]


`reshape(a, newshape)`: It gives a new shape to an array `a` without changing its data.

In [30]:
print(np.reshape(b,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


## Decoding Assignment 4

### Assignment 4

Q. Use recursion to design a program that can automatically place its chance in the previously built tic-tac-toe game and always wins the game.
Hint: https://www.neverstopbuilding.com/blog/minimax

Example:
```
In: 
Choose X or O
Player: X

Player: 4
Out:
   |   |
-----------
   | X |
-----------
   |   |

Out: 
Computer places O at 2
   |   | O
-----------
   | X |
-----------
   |   |

In: 
Player: 0
Out:
 X |   | O
-----------
   | X |
-----------
   |   |
   
Out: 
Computer places O at 9
 X |   | O
-----------
   | X | 
-----------
   |   | O

In:
Player: 5
Out: 
 X |   | O
-----------
   | X | X
-----------
   |   | O

Out: 
Computer places O at 3
 X |   | O
-----------
 O | X | X
-----------
   |   | O

In:
Player: 1
Out: 
 X | X | O
-----------
 O | X | X
-----------
   |   | O
   
Out: 
Computer places O at 7
 X | X | O
-----------
 O | X | X
-----------
   | O | O

In:
Player: 6
Out: 
 X | X | O
-----------
 O | X | X
-----------
 X | O | O

The match is drawn!!!
```


Let's first define a scoring criteria

```
def score(game)
    if game.win?(@player)
        return 1
    elsif game.win?(@opponent)
        return -1
    else
        return 0
    end
end
```

and minimax algorithm

```
def minimax(game)
    return score(game) if game.over?
    scores = [] # an array of scores
    moves = []  # an array of moves

    # Populate the scores array, recursing as needed
    game.get_available_moves.each do |move|
        possible_game = game.get_new_state(move)
        scores.push minimax(possible_game)
        moves.push move
    end

    # Do the min or the max calculation
    if game.active_turn == @player
        # This is the max calculation
        max_score_index = scores.each_with_index.max[1]
        @choice = moves[max_score_index]
        return scores[max_score_index]
    else
        # This is the min calculation
        min_score_index = scores.each_with_index.min[1]
        @choice = moves[min_score_index]
        return scores[min_score_index]
    end
end
```

Let's take a smaller game. Tic-tac-toe with only 4 sides and diagonal winning is not allowed. So what will be the tree/chances of it.

```
1. | X |   |   2. |   | X |  3. |   |   |  4. |   |   |
   ---------      ---------     ---------     ---------
   |   |   |      |   |   |     | X |   |     |   | X |
       +1             +1            +1            +1
   
1.1. | X | O |   1.2. | X |   |  1.3 | X |   | 
     ---------        ---------      --------- 
     |   |   |        | O |   |      |   | O |
         +1               +1             +2
2.1. | O | X |   2.2. |   | X |  2.3 |   | X | 
     ---------        ---------      --------- 
     |   |   |        | O |   |      |   | O |
         +1               +2             +1
3.1. | O |   |   3.2. |   | O |  3.3 |   |   | 
     ---------        ---------      --------- 
     | X |   |        | X |   |      | X | O |
         +1               +2             +1
4.1. | O |   |   4.2. |   | O |  4.3 |   |   | 
     ---------        ---------      --------- 
     |   | X |        |   | X |      | O | X |
         +2               +1             +1
        
1.1.1. | X | O |   1.1.2.| X | O |   1.2.1. | X | X |  1.2.2. | X |   |  1.3.1. | X | X |  1.3.2. | X |   |
       ---------         ---------          ---------         ---------         ---------         ---------
       | X |   |         |   | X |          | O |   |         | O | X |         |   | O |         | X | O |
          WIN               DRAW               WIN               DRAW              WIN                WIN
2.1.1. | O | X |   2.1.2.| O | X |   2.2.1. | X | X |  2.2.2. |   | X |  2.3.1. | X | X |  2.3.2. |   | X |
       ---------         ---------          ---------         ---------         ---------         ---------
       | X |   |         |   | X |          | O |   |         | O | X |         |   | O |         | X | O |
          DRAW              WIN                WIN               WIN               WIN               DRAW
```